import { describe, it, expect, vi, beforeAll, afterAll, beforeEach, afterEach } from "vitest";
import fs from "fs/promises";
import path from "path";
import { pathToFileURL } from "url";
import serverActions, { generateClientProxy } from "../src/index.js";

// Temp dir must live inside the project root so sanitizePath containment passes,
// but NOT inside node_modules: files there are never treated as server actions.
const tempDir = path.join(process.cwd(), "vsa-test-tmp", `vsa-proxy-${process.pid}-${Date.now()}`);

const routeTransform = (filePath, functionName) => {
	const base = path.basename(filePath).replace(/\.server\.(js|ts)$/, "");
	return `${base}/${functionName}`;
};

function jsonResponse(status, body) {
	return {
		ok: status >= 200 && status < 300,
		status,
		json: async () => body,
	};
}

let enhancedProxy; // module generated by the enhanced (default) proxy generator
let fallbackProxy; // module generated by the fallback proxy generator
let fetchMock;

beforeAll(async () => {
	await fs.mkdir(tempDir, { recursive: true });

	// Enhanced proxy: the code path real users hit - generate it through the
	// plugin's load() hook against a real server file
	const serverFile = path.join(tempDir, "todo.server.js");
	await fs.writeFile(serverFile, `export async function addTodo(text) { return { text }; }\n`);

	const plugin = serverActions({ routeTransform });
	const enhancedCode = await plugin.load(serverFile);
	expect(enhancedCode).toContain("export async function addTodo");

	const enhancedFile = path.join(tempDir, "enhanced-client.mjs");
	await fs.writeFile(enhancedFile, enhancedCode);
	enhancedProxy = await import(pathToFileURL(enhancedFile).href);

	// Fallback proxy: generated directly (load() only uses it when the AST
	// parser yields no detailed function info)
	const fallbackCode = generateClientProxy(
		"todo",
		["addTodo"],
		{ apiPrefix: "/api", routeTransform },
		"todo.server.js",
	);
	const fallbackFile = path.join(tempDir, "fallback-client.mjs");
	await fs.writeFile(fallbackFile, fallbackCode);
	fallbackProxy = await import(pathToFileURL(fallbackFile).href);
});

afterAll(async () => {
	await fs.rm(tempDir, { recursive: true, force: true });
});

beforeEach(() => {
	fetchMock = vi.fn();
	vi.stubGlobal("fetch", fetchMock);
	// Silence the generated proxies' console chatter
	vi.spyOn(console, "log").mockImplementation(() => {});
	vi.spyOn(console, "error").mockImplementation(() => {});
	vi.spyOn(console, "warn").mockImplementation(() => {});
});

afterEach(() => {
	vi.unstubAllGlobals();
	vi.restoreAllMocks();
});

describe.each([
	["enhanced proxy", () => enhancedProxy],
	["fallback proxy", () => fallbackProxy],
])("Generated client proxy runtime (%s)", (label, getModule) => {
	it("POSTs the arguments as a JSON array to the module route", async () => {
		fetchMock.mockResolvedValue(jsonResponse(200, { text: "hi" }));

		const result = await getModule().addTodo("hi");

		expect(fetchMock).toHaveBeenCalledTimes(1);
		const [url, init] = fetchMock.mock.calls[0];
		expect(url).toBe("/api/todo/addTodo");
		expect(init.method).toBe("POST");
		expect(init.headers).toEqual({ "Content-Type": "application/json" });
		expect(init.body).toBe(JSON.stringify(["hi"]));
		expect(result).toEqual({ text: "hi" });
	});

	it("returns undefined for 204 No Content responses", async () => {
		fetchMock.mockResolvedValue({
			ok: true,
			status: 204,
			json: async () => {
				throw new Error("no body");
			},
		});

		await expect(getModule().addTodo("hi")).resolves.toBeUndefined();
	});

	it("surfaces the server error MESSAGE, not Error('true')", async () => {
		// Dev and prod error envelopes both use error: true (boolean) with the
		// human-readable text in message
		fetchMock.mockResolvedValue(
			jsonResponse(400, {
				error: true,
				status: 400,
				message: "Validation failed",
				code: "VALIDATION_ERROR",
				timestamp: new Date().toISOString(),
				details: { validationErrors: [{ path: "text", message: "Required" }] },
			}),
		);

		let thrown;
		try {
			await getModule().addTodo();
		} catch (error) {
			thrown = error;
		}

		expect(thrown).toBeInstanceOf(Error);
		expect(thrown.message).toBe("Validation failed");
		expect(thrown.message).not.toBe("true");
		expect(thrown.status).toBe(400);
	});

	it("preserves server errors that carry no details (e.g. production 500s)", async () => {
		fetchMock.mockResolvedValue(
			jsonResponse(500, {
				error: true,
				status: 500,
				message: "Internal server error",
				code: "INTERNAL_ERROR",
				timestamp: new Date().toISOString(),
			}),
		);

		let thrown;
		try {
			await getModule().addTodo("hi");
		} catch (error) {
			thrown = error;
		}

		expect(thrown.message).toBe("Internal server error");
		expect(thrown.status).toBe(500);
	});

	it("wraps network errors with the function name (no ReferenceError)", async () => {
		fetchMock.mockRejectedValue(new Error("connection refused"));

		let thrown;
		try {
			await getModule().addTodo("hi");
		} catch (error) {
			thrown = error;
		}

		expect(thrown).toBeInstanceOf(Error);
		expect(thrown).not.toBeInstanceOf(ReferenceError);
		expect(thrown.message).toBe("Failed to execute server action 'addTodo': connection refused");
		expect(thrown.originalError).toBeInstanceOf(Error);
	});

	it("throws a useful error when the error response body is not JSON", async () => {
		fetchMock.mockResolvedValue({
			ok: false,
			status: 502,
			json: async () => {
				throw new Error("invalid json");
			},
		});

		let thrown;
		try {
			await getModule().addTodo("hi");
		} catch (error) {
			thrown = error;
		}

		expect(thrown).toBeInstanceOf(Error);
		expect(thrown).not.toBeInstanceOf(ReferenceError);
		expect(typeof thrown.message).toBe("string");
		expect(thrown.message.length).toBeGreaterThan(0);
	});
});
